### ISSUE TITLE
Add cancel button 

### ISSUE THREAD

**Issue by mnelson4** [mnelson4/printmyblog#27]
Yes users can already press “back” in their browser, but they don’t know if that will break something (in some other services it does) so it’s probably a good addition.
See https://wordpress.org/support/topic/works-great-if-site-supports-what-it-needs/

**Comment by mjluser1** [comment]
Hi Mike!  I did not see an issue regarding the plugin's hanging because the REST API had no jason, so I am writing this here.  My main site is PhysicsSpot.com, which worked fine.  The problem was on the staging (clone) site I had created using the WP Staging plugin. Apparently whatever made your plugin hang was something done by WP Staging.  I think you might find what you need in its documentation. As I mentioned, your plugin hung on the "Initializing" display and thus probably never got to the error-display section of your code.  Thanks again for the great plugin!

**Comment by mnelson4** [comment]
Hellol again @mjluser1! 
Ah that's helpful info, thanks. I expect that will help me to reproduce the problem, and either fix it or give a better error message. I'm going on a trip for the rest of this week and won't get to it before then.

Regarding the missing images, did you see the [FAQ "Some images aren’t appearing"](https://wordpress.org/plugins/print-my-blog/#some%20images%20aren%E2%80%99t%20appearing)? If that doesn't make them appear, could you please create a new issue (in GitHub or WordPress.org, whichever you prefer)?

**Comment by mnelson4** [comment]
Ok the cancel button has been added in 1.9.3.
I created a separate issue for WP staging issue: https://github.com/mnelson4/printmyblog/issues/28
