### ISSUE TITLE
File system access is not allowed.

### ISSUE THREAD

**Issue by greggno** [mnelson4/printmyblog#272]
I got everything set up like I wanted and then clicked Download Test PDF under Pro Print Service and I get the error:
"File system access is not allowed."

Happy to pay for the Pro version but I thought I understood that a limited test was allowed first?

Please advise, thank you.
GG
                                 

```
{"php":"7.3.30","wp":"5.8","site_url":"https://www.stumblingoverstardust.com","home_url":"https://www.stumblingoverstardust.com","language":"en_US","public":"1","environment_type":"production","plugins_active":{"Akismet Anti-Spam":"4.1.11 by Automattic ","Child Theme Configurator":"2.5.8 by Lilaea Media ","Classic Editor":"1.6.2 by WordPress Contributors ","Google Analytics for WordPress by MonsterInsights":"7.18.0 by MonsterInsights ","Gutenberg":"11.4.0 by Gutenberg Team ","Jetpack":"10.0 by Automattic ","MOJO Marketplace":"1.5.8 by Mike Hansen ","MPL - Publisher":"1.29.2 by Ferran Figueredo ","Print, PDF & Email by PrintFriendly":"4.1 by Print, PDF, & Email by PrintFriendly ","Print My Blog":"3.4.7 by Michael Nelson ","Simple Lightbox":"2.8.1 by Archetyped ","SmartCrawl":"2.12.0 by WPMU DEV ","UpdraftPlus - Backup/Restore":"1.16.61 by UpdraftPlus.Com, DavidAnderson ","WP-Optimize - Clean, Compress, Cache":"3.1.12 by David Anderson, Ruhani Rabin, Team Updraft ","WP-Print":"2.58.1 by Lester 'GaMerZ' Chan ","WPForms Lite":"1.6.9 by WPForms ","WP Spell Check":"9.2 by WP Spell Check "},"active_theme":{"name":"SOS (blog-diary-child)","version":"1.1.5.1588886043","author":"GG4orce","author_website":"http://www.gg4orce.com/","parent_theme":"Blog Diary (blog-diary)","theme_features":"core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, footer-widgets, post-thumbnails, menus, html5, custom-background, custom-logo, customize-selective-refresh-widgets, editor-style, editor-color-palette, align-wide, editor-font-sizes, editor-styles, wp-block-styles, custom-header, jetpack-responsive-videos, widgets"},"debug":false,"post_max_size":"516M","upload_max_size":"512M","effective_max_size":536870912,"ssl":true,"multisite":false,"projects":[{"title":"Stumbling Over Stardust - Ebook 2019-2021","generations":{"digital_pdf":"http://www.stumblingoverstardust.com/wp-content/uploads/pmb/generated/xXKze1HKm3kSJX1zDa7L/digital_pdf/stumbling-over-stardust-ebook-2019-2021.html?uniqueness=1630685294"},"meta":{"_pmb_title":"Stumbling Over Stardust - eBook 2019-2021","_pmb_byline":"Dudley Crawford","_pmb_cover_preamble":"With all respect to heaven, the scene of the miracle is here, among us.","_pmb_error_digital_pdf":"File system access is not allowed."},"designs":{"digital_pdf":{"title":2546,"template":"Mayer Digital PDF","meta":{"_pmb_page_per_post":"1","_pmb_post_header_in_columns":"","_pmb_dividing_line":"","_pmb_images_full_column":"","_pmb_no_extra_columns":"1","_pmb_image_placement":"snap-unless-fit","_pmb_use_theme":"1","_pmb_custom_css":null,"_pmb_powered_by":"1"}},"print_pdf":{"title":2543,"template":"Classic Print PDf","meta":{"_pmb_header_content":["title","subtitle","url","date_printed"],"_pmb_post_content":["title","published_date","categories","featured_image","content"],"_pmb_page_per_post":"1","_pmb_main_header_font_size":"4em","_pmb_header_font_style":"palatino linotype","_pmb_font_size":"10pt","_pmb_font_style":"times","_pmb_paragraph_indent":"1","_pmb_image_size":"400","_pmb_default_alignment":"center","_pmb_image_placement":"snap-unless-fit","_pmb_page_width":"8.5in","_pmb_page_height":"11in","_pmb_internal_links":"parens","_pmb_page_reference_text":"(see page %s)","_pmb_internal_footnote_text":"See page %s.","_pmb_external_links":"remove","_pmb_footnote_text":"See %s.","_pmb_use_theme":"","_pmb_custom_css":null,"_pmb_powered_by":"1"}}}}]}
```

**Comment by mnelson4** [comment]
Hi @greggno, thanks for reporting this issue properly. That’s a straight-up error, not me trying to upsell you on something! 
I’m pretty sure the PDF-creation service (printmy.blog passes it onto docraptor.com) thinks you were trying to access something on their file system. I will try to debug with the info you’ve sent and will let you know over the coming few days (I’m currently in a bit of a time crunch and this might be tricky to debug.)

**Comment by greggno** [comment]
Thanks @mnelson4 for sorting that out when you get a chance. It seems like exactly the right tool for what I need.
I'll work on tweaking my formatting in the meantime and wait to hear back from you. 
Thanks, GG

**Comment by mnelson4** [comment]
Ok I found the problem. There's a little problem with your HTML: there's an image tag which points to an image on your local machine. 
Ie, there's this HTML `<img loading="lazy" align="left" height="1" hspace="12" src="file:///C:/Users/dudle/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg" v:shapes="Picture_x0020_2064" width="1" />` on[ the post "Cowboys and Angels"](https://www.stumblingoverstardust.com/cowboys-and-angels/). Because the image is only 1 pixel wide and 1 pixel tall, it's really not noticeable. But it's causing PMB to try to access the filesystem on the site running the print service, which is causing an error before it gets into anything it shouldn't.
Also, [the post "There must be a mistake" ](https://www.stumblingoverstardust.com/there-must-be-a-mistake/)has a similar bit of hidden HTML: `<v:imagedata o:title="" src="file:///C:/Users/dudle/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg"></v:imagedata>`.
Any idea why that's there? I suspect that should be removed.

Either way, I'll also try to make PMB automatically fix this in the next update...

**Comment by mnelson4** [comment]
Hey @greggno do you want to try the upcoming version of PMB to confirm it resolves the issue for you? (I somehow didn't manage to make that problem happen for me, even when I setup some problematic HTML like what I pointed out earlier.)
Here's how to test:

1. Download the new version from here: https://github.com/mnelson4/printmyblog/archive/refs/heads/FET/duplicate.zip
2. Go to your WordPress dashboard, click plugins, then "add new", then "upload" and select the zip file you just downloaded
3. Deactivate the previous version Print My Blog
4. Activate the new version of Print My Blog
5. Regenerate the document from the "Generate" page
6. From the print-page, click to download the test PDF again. It should work this time.

Once you are done trying it out, just deactivate the new version, then delete it (do NOT press the "Delete All Data", that will remove all your settings). Then activate the previous version again. You will then be able to receive automatic updates as usual.

**Comment by mnelson4** [comment]
Oh also you may want to either uncheck "Apply Website Theme" on the "Customize Design" step (see the very bottom of https://printmy.blog/user-guide/pdf-design/mayer-magazine-digital-pdf/) or adding some custom CSS like `body{background:white;}`. But please do note that I only offer support for "Apply Website Theme" for business plans (because themes are often a major headache to get working properly in print) so it's usually easier to just turn them off. [If you want a different font than the default, it just takes a little custom CSS](https://printmy.blog/user-guide/design-layout/how-to-customize-fonts/) so that's usually an easier approach.

**Comment by greggno** [comment]
Thank you Mike. Will give it a shot.
I appreciate your time,
Gregg

**Comment by mnelson4** [comment]
Actually, I've just released the fix in PMB 3.5.0, so no need to download a different version, just update to 3.5.0 from your WordPress admin dashboard (on the plugins page or update page). I'm hopeful your issue will be resolved even without needing any more work from you than updating and re-generating the print-page.

**Comment by mnelson4** [comment]
I’m pretty sure this issue was fixed so am closing it. But if it isn’t feel free to reopen

**Comment by mnelson4** [comment]
This error came up again. 3.10.0 automatically tries to fix these
