### ISSUE TITLE
Not so much an issue but a request

### ISSUE THREAD

**Issue by tamarw** [mnelson4/printmyblog#275]
Hey - just curious - I've enabled everything but I think because I am using Elementor, there's a conflict.

Any recommendation on how to get around that? I'd love to make a shortcode that integrates the features of the plugin to my Elementor templates.

Thanks much.

**Comment by mnelson4** [comment]
Hi @tamarw, are you just wanting to add the print buttons onto your posts or pages?
If so, you can also try using the shortcode `[pmb_print_buttons]`. It's mentioned at the end of this FAQ: https://wordpress.org/plugins/print-my-blog/#how%20do%20i%20show%20the%20print%20buttons%20on%20posts%20or%20pages%3F
Does that help?

If you're wanting to do something else (like print your entire website), can you maybe describe the conflict you're getting abit more?

**Comment by tamarw** [comment]
So I'm setting it up in Elementor, using the Meta Data item, and the link is going to about:blank#blocked. I figure I have no idea how to implement this properly :)

I just want some of my Elementor pages to be friendly as ctrl+p causes loss of some elements. Hoping PMB helps.

**Comment by mnelson4** [comment]
Hi @tamarw, yes I think I understand what you're hoping to achieve, and it sounds like you're probably going about it the right way, but have either missed a detail or there is a plugin conflicting that's make it not work.
For clarity, I just created this video to show how to use PMB with Elementor: https://youtu.be/sMlCHow7Hok
Also, I think by "Meta Data Item" you mean "Custom Fields". Here's a screenshot showing how I add print buttons to a page by adding a custom field called "pmb_buttons" with the value "show": https://i.imgur.com/w608h5t.png

If that doesn't help, could you please send me some screenshots showing what you're doing, and what the result is?

**Comment by tamarw** [comment]
Not exactly :) Here's a screencast. Lemme know if this helps. https://www.berrycast.com/conversations/c3a3f284-dcf2-5509-b986-cda0e06925af

**Comment by mnelson4** [comment]
Hi @tamarw, yes that video does help quite a lot.
I believe the problem is that you're supposed to be using a shortcode that will return a URL (eg `https://printmy.blog`), but the `[pmb_print_buttons]` shortcode instead returns a bunch of HTML (eg `<a href="https://printmy.blog">Print Now</a>`). I bet Elementor has kinda detected this discrepancy and so removed the HTML and replaced it with... garbley-gook.
Lemme see if I can make a shortcode that will do what you want...

**Comment by tamarw** [comment]
Sweet, that would be pretty awesome, thanks.

**Comment by mnelson4** [comment]
1. Download the new version from here: https://github.com/mnelson4/printmyblog/archive/refs/heads/FET/url-shortcode.zip
2. Go to your WordPress dashboard, click plugins, then "add new", then "upload" and select the zip file you just downloaded
3. Deactivate the previous version Print My Blog
4. Activate the new version of Print My Blog
5. Add the shortcode `[pmb_print_page_url]` to the "Post Info" widget (instead of the other shortcode you were using). If that doesn't work you can also try `[pmb_print_page_url add_protocol=0]`

I'm sorry I couldn't test it because that widget is only available in Elementor Pro, which I don't have.

Once you are done trying it out, just deactivate the new version, then delete it (do NOT press the "Delete All Data", that will remove all your settings). Then activate the previous version again. You will then be able to receive automatic updates as usual.

**Comment by tamarw** [comment]
Hmm, would using the Post Info widget change the layout I'm working for? I assume the shortcode would work in the same setup as you see in my video, no? Thank you for doing this!

**Comment by mnelson4** [comment]
Hi @tamarw, sorry I thought "Post Info" was the widget you were using. But yes, do exactly what you did before, but use `[pmb_print_page_url]` instead of `[pmb_print_buttons]`. If that doesn't send you to the right URL for printing, try `[pmb_print_page_url add_protocol=0]`.
If neither of those work, can you direct me to the page where you're having trouble?

**Comment by tamarw** [comment]
You got it! This is legit super cool - thank you so much for this!

**Comment by mnelson4** [comment]
Nice! Out of curiosity, did you need to use `[pmb_print_page_url add_protocol=0]`? (or just `[pmb_print_page_url]`?)
I expect to release this soon to everyone else

**Comment by tamarw** [comment]
[pmb_print_page_url] worked for me. 😁

**Comment by mnelson4** [comment]
Right on. Case closed!
Well, almost. I’ll release the change to everyone next time I have 20 minutes on my laptop. Then you can deactivate this version (which requires a license for upgrades) and just reactivate the version from WordPress.org

**Comment by tamarw** [comment]
Many thanks Mike!

**Comment by mnelson4** [comment]
Ok 3.6.0 has been released on WordPress.org! So @tamarw you can deactivate the version you tried out and delete it (but don't press "Delete All Data", that's different). Then update the version on WordPress.org (or re-install it.)
After that, you'll be back on track to receive automatic updates.

If you have 30 minutes, I'd like to do an pseudo interview showing how you're using PMB in order to make a blog post about it. If you have time, here's the "interview": https://printmy.blog/surveys/interesting-use-case-interview/
Alternatively, [a nice review on WordPress.org would be good too.](https://wordpress.org/support/plugin/print-my-blog/reviews/#new-post)
Ok, take care!

**Comment by tamarw** [comment]
Lemme see what I can do on the use case interview ;) I want to launch a specific really long blog post first. Then I might sign up for that too. Thanks again!

**Comment by mnelson4** [comment]
Yeah no worries if you don't get around to it anytime soon, the interview is a bit time-consuming. The review on wp.org was much appreciated!
