### ISSUE TITLE
trying to generate ebook but button greyed out

### ISSUE THREAD

**Issue by loujedw** [mnelson4/printmyblog#320]
I am trying to generate a ebook but the button is greyed out

![image](https://user-images.githubusercontent.com/102734643/161380938-7dd4bad2-9846-40e6-a3be-ee84ee578a28.png)

**Comment by mnelson4** [comment]
The URL is http://mygorgeousboys.com/wp-content/uploads/pmb/generated/zovUeX7jlV7cwNZgNQ7o/epub/my-gorgeous-boys-blog-2.html
Its actually working but there are hundreds of embedded videos and images so its taking minutes to prepare the document... and there are some images on different domains so they aren't loading

**Comment by mnelson4** [comment]
I suspect the project is just too big. The file may be gigabytes big... It would probably be good to try making a different document for each year

**Comment by mnelson4** [comment]
The ePub was too big. Since then I made some updates that allow PMB to make much larger ePub files (before it had a problem with ePubs over a few megabytes; now it manages at least hundreds of megabytes, and I suspect it could handle a gigabyte or two.)
Unfortunately, the reporter of this issue's hosting has ran out and so they weren't able to confirm the fix on time. But I do believe the issue has been resolved according to my testing.
