### ISSUE TITLE
Error Message after plugin update

### ISSUE THREAD

**Issue by uwefunk** [mnelson4/printmyblog#68]
Hi @mnelson4 Today i updated the plugin for my website: digitales-fuer-einsteiger.de After update I've got the error message as shown in the screenshot.

I had to deactivate the plugin. Any idea?

Best regards, Uwe
<img width="1303" alt="Bildschirmfoto 2020-05-08 um 10 34 35" src="https://user-images.githubusercontent.com/38373905/81403475-c30d2680-9133-11ea-847f-b0e127d7cd59.png">

**Comment by mnelson4** [comment]
Hmm that seems related to my changes in 2.4.0 which allow you to save frontend print button settings. But those warnings like that should only come up if you have `WP_DEBUG` on, which you probably shouldn't on a live site.

Either way, I'll try to fix those warnings asap...

**Comment by mnelson4** [comment]
Hi @uwefunk I just published 2.4.1 which fixes those warnings. Sorry that happened but thanks for reporting it.
By the way, I don't know if you saw it already, but I'm asking for feedback for the pro version in exchange for a discount (or lifetime license, while they last) when its released. See https://printmy.blog/2020/04/27/get-a-major-discount-for-print-my-blog-pro-by-becoming-a-founding-member/. I think because you're on the list you should have gotten a couple emails about it with a link to the survey

**Comment by uwefunk** [comment]
Hi @mnelson4 many thanks for the quick solution. With the update it works fine again. Meanwhile the output when printing looks pretty nice.

I also subscribed to the NL and filled the survey meanwhile. Looking forward to the PRO version.
